import Head from "next/head";
import { useState, useEffect } from "react";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import ReactTextTransition, { presets } from "react-text-transition";

const inter = Inter({ subsets: ["latin"] });

const names = ["Jitin Dodd", "Jitin ਡੋਡ", "ਜਿਤਿਨ Dodd", "ਜਿਤਿਨ ਡੋਡ"];

export default function Home() {
  const [index, setIndex] = useState(0);

  useEffect(() => {
    const intervalId = setInterval(
      () => setIndex((index) => (index + 1) % names.length),
      5000 // every 5 seconds
    );
    return () => clearTimeout(intervalId);
  }, []);

  return (
    <>
      <Head>
        <title>Jitin Dodd</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {/* <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.tsx</code>
          </p>

          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{" "}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div> */}

        {/* <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div> */}

        <div className={styles.me}>
          <div className={styles.name}>
            <h2>
              Hey! I'm{" "}
              <ReactTextTransition inline>{names[index]}</ReactTextTransition>
            </h2>
          </div>
          {/* ਜਿਤਿਨ ਡੋਡ */}

          <h3>You can find me on:</h3>
          <ul>
            <li>
              <a
                href="https://instagram.com/jitindodd"
                target="_blank"
                rel="noopener noreferrer"
              >
                Instagram: <span className={styles.handle}>@jitindodd</span>
              </a>
            </li>

            <li>
              <a
                href="https://twitter.com/jitin_dodd"
                target="_blank"
                rel="noopener noreferrer"
              >
                Twitter: <span className={styles.handle}>@jitin_dodd</span>
              </a>
            </li>

            <li>
              <a
                href="https://www.youtube.com/@doddtv"
                target="_blank"
                rel="noopener noreferrer"
              >
                YouTube: <span className={styles.handle}>@dodd</span>
              </a>
            </li>

            <li>
              <a
                href="https://www.linkedin.com/in/jitindodd"
                target="_blank"
                rel="noopener noreferrer"
              >
                LinkedIn: <span className={styles.handle}>@jitindodd</span>
              </a>
            </li>

            <li>
              <a
                href="https://www.goodreads.com/user/show/59516132-jitin"
                target="_blank"
                rel="noopener noreferrer"
              >
                Goodreads: <span className={styles.handle}>@jitin</span>
              </a>
            </li>

            <li>
              <a
                href="https://github.com/jitindodd"
                target="_blank"
                rel="noopener noreferrer"
              >
                GitHub: <span className={styles.handle}>@jitindodd</span>
              </a>
            </li>

            <li>
              <a href="mailto:jitindodd@gmail.com">
                Email:{" "}
                <span className={styles.handle}>jitindodd@gmail.com</span>
              </a>
            </li>

            <li>
              <a
                href="https://rainbow.me/jitin.eth"
                target="_blank"
                rel="noopener noreferrer"
              >
                ENS: <span className={styles.handle}>jitin.eth</span>
              </a>
            </li>

            <li className={styles.emoji}>🦕</li>
          </ul>
        </div>

        {/* <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Docs <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Learn <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Templates <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Deploy <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div> */}
      </main>
    </>
  );
}
